### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#1]
I like Devoll. However, Can you tell me how much it can be hacked so that we can add/subtract elements of it as required?

**Comment by sabman** [comment]
Color pallet can easily be modified. The rest, I'd say let's stick to the default version for now as it has everything we need (maybe too much). 

Plase see: https://geografia-au.github.io/company-site-jekyll//index.html

Note how the placeholder images have their dimensions showing. The main job now is to gather all the graphics/images that fit these dimensions and don't clash with the colors
