### ISSUE TITLE
Provide Content: Contact Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#10]
https://geografia-au.github.io/contact
- [x] background image 2400x1800
- [x] title text (if you want to modify it)
- [x] subtitle text (if you want to modify it)

---

For @geografia-au/web 
Remove contact for and simply add contact details with:
- [x] Link to google Maps for the addresses malaysia: https://goo.gl/maps/UzynddLqvv62 melbourne https://goo.gl/maps/J2vH2GUSR7s
- [x] use mailto link for email
- [x] use tel: link for phone numbers

for content see http://geografia.com.au/#contact

**Comment by DrKLJ** [comment]
Text: "Drop by, call or send an email us"

**Comment by DrKLJ** [comment]
@Cesar-Nicolas, can you find an image for us? I've checked what we have and can't see anything that works. I would have thought a map showing our street address, but we already have one.

**Comment by sabman** [comment]
@Cesar-Nicolas you can search on flick for images without copyrights 
https://www.flickr.com/search/?text=maps%20melbourne&rb=1&license=7%2C9%2C10

Or you can use http://staticmapmaker.com/ to create a cool image like this one:

![](https://api.mapbox.com/v4/mapbox.wheatpaste/geojson%28%7B%0A%20%20%22type%22%3A%20%22FeatureCollection%22%2C%0A%20%20%22features%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22Geografia%20Pty%20Ltd%22%2C%0A%20%20%20%20%20%20%20%20%22address%22%3A%20%22Suite%201%2C%20Level%2021%2C%2015%20Collins%20St%2C%20Melbourne%2C%20VIC%203000%22%2C%0A%20%20%20%20%20%20%20%20%22telephone%22%3A%20%22%2B61%203%209329%209004%22%2C%0A%20%20%20%20%20%20%20%20%22email%22%3A%20%22info%40geografia.com.au%22%2C%0A%20%20%20%20%20%20%20%20%22website%22%3A%20%22http%3A%2F%2Fgeografia.com.au%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22Polygon%22%2C%0A%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20144.97318267822266%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20-37.81367236268372%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20144.97332751750946%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20-37.8136215074211%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20144.97344285249707%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20-37.813860950643466%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20144.97329533100128%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20-37.813903329893975%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20144.97318267822266%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20-37.81367236268372%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22Geografia%20Pty%20Ltd%22%2C%0A%20%20%20%20%20%20%20%20%22address%22%3A%20%22Suite%201%2C%20Level%2021%2C%2015%20Collins%20St%2C%20Melbourne%2C%20VIC%203000%22%2C%0A%20%20%20%20%20%20%20%20%22telephone%22%3A%20%22%2B61%203%209329%209004%22%2C%0A%20%20%20%20%20%20%20%20%22email%22%3A%20%22info%40geografia.com.au%22%2C%0A%20%20%20%20%20%20%20%20%22website%22%3A%20%22http%3A%2F%2Fgeografia.com.au%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22Point%22%2C%0A%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20144.9733141064644%2C%0A%20%20%20%20%20%20%20%20%20%20-37.81376135930903%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D%29/144.9733141064644,-37.81376135930903,17/640x400@2x.png?access_token=pk.eyJ1Ijoic2FiIiwiYSI6IlB2NDg2NDQifQ.-0pGhgotPTf4OzAZRO6eUg)

**Comment by sabman** [comment]
I tried the colored map but that doesn't work. For background images they must blend into the background otherwise the text becomes unreadable. So I have now updated to https://geografia-au.github.io/contact/

**Comment by ziprandom** [comment]
4d87ef9974b93182f928d87065c49d8cdd78abf0,
34800782380f097b2340ed0a1cb0915ffa68a55a
