### ISSUE TITLE
Provide Content: Lab Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#11]
see https://geografia-au.github.io/lab/
- [x] provide background image
- [x] provide tile 
- [x] provide subtitle

refs #7

**Comment by DrKLJ** [comment]
@sabman Is this Lab page or projects? It goes to projects. 
Also, how does this relate to the 'our works' section on home page? Is works a cutdown view of our projects?

**Comment by sabman** [comment]
Yes sorry it should say projects. I think it's pretty much done.
