### ISSUE TITLE
Cleanup Projects / Works Section

### ISSUE THREAD

**Issue by ziprandom** [geografia-au/geografia-au.github.io#14]
At the moment we show all the [projects/works](https://geografia-au.github.io/projects/) content that was present on the old site. However most of the images look dirty and the projects seem to lack the date on which they were completed. As there are too many anyway we suggest to: 
- Pick the ones that are worth showing in the portfolio (the outstanding ones)
- Make sure images & texts are of high quality and the times are correct. 

The respective markdown documents can be found [here](https://github.com/geografia-au/geografia-au.github.io/tree/master/source/content/projects), pictures should be placed [here](https://github.com/geografia-au/geografia-au.github.io/tree/master/source/static/img/projects) --> please also remove the pictures, that are no longer needed when you create a pull-request. 

If you need any assistence don't hessitate to contact @sabman or @ziprandom

**Comment by DrKLJ** [comment]
@sabman How many can, or should we pick?

**Comment by sabman** [comment]
@DrKLJ you may pick all as long as we can have the following requirements met:
- [ ] high quality images (or an appropriate high quality placeholder if you can't find the original images)
- [ ] ranking of the project so we know the order in which to show them

**Comment by sabman** [comment]
@DrKLJ I would also like to add to this that we should have black and white versions of the thumbnails on the page with the list so that colors don't clash. Maybe we can show the colored version on hover

**Comment by DrKLJ** [comment]
@sabman. @ziprandom 
1. What is the best way to pick the best projects. I would like to rank order them offline and present this list to you, but perhaps there is some way to sort the markdown documents in order? That would be faster. 
2. Can I change the date in the date column of each table in the markdown documents and can it just be a year, rather than a full date (I'd like just to have the year completed)? 
3. Note, Cesar will work on this on Tuesday: finding high quality images and making them Black and White and uploading.

**Comment by sabman** [comment]
1. https://github.com/geografia-au/geografia-au.github.io/blob/master/source/content/projects/advancing_orbost_economic_development_strategy.md You can add another field for rank here

**Comment by DrKLJ** [comment]
@cesar I have put the date (year) and whether the project is in or out into the source file (the Excel file  Dropbox (Geografia)\Company Website\Our Projects), I've also done the first one (plus a couple of others) to show how its done (change the date column to show just the year and add a new column 'in or out'). Over to you, Cesar. Add in the details and then load up higher quality B&W images for each project.

**Comment by sabman** [comment]
@DrKLJ  re:

> 2 Can I change the date in the date column of each table in the markdown documents and can it just be a year, rather than a full date (I'd like just to have the year completed)?

I have will take care of this - you should still provide a complete date in the given format but I have changed the code to only show the year the project was done.

**Comment by sabman** [comment]
@DrKLJ with rank you need to give it a number. so starting at 1 (being the most important) and so on...

**Comment by sabman** [comment]
STATUS: 
- [x] awaiting @Cesar-Nicolas to provide HQ image

PS. I would add if you can't find the original images just make some new ones up by creating screenshots from QGIS or even the City Atlas

**Comment by Cesar-Nicolas** [comment]
Images sorted by Year then Project Name (A-Z) can be found at
https://www.dropbox.com/sh/w9qui4j6aobm97l/AACpxYKL0iHQFQVFLFQSbeasa?dl=0

However in testing the project viewer, I've found an issue that I think it might be worth considering regarding the template. If you think that it's a good idea, then I'll format all the pictures into the same dimension

![project images mockup](https://cloud.githubusercontent.com/assets/20567917/19096507/a58ca0d6-8ae8-11e6-95eb-e8cdd9f031ed.png)

**Comment by sabman** [comment]
@Cesar-Nicolas thanks for this - ideally you should not have changed the image names and just replaced the existing images with exactly the same name, just higher resolution and everything would just work. I'll now have to go through and figure out which image belongs to which project article. For future reference see https://github.com/geografia-au/geografia-au.github.io/blob/master/source/content/projects/ note the reference to image in each post

**Comment by sabman** [comment]
@Cesar-Nicolas @DrKLJ we are still missing some high resolution images: 
- [ ] impact of Art Spaces in Melbourne - Affordable_Spaces.jpg

![affordable_spaces](https://cloud.githubusercontent.com/assets/1907/19110666/89921740-8afb-11e6-8d73-7f4ed9c6a085.jpg)

**Comment by sabman** [comment]
@Cesar-Nicolas I agree about the dimensions. We can continue to improve that. I'll wrap up this issue and we can open a new issue for that. I'd like to get the site live ASAP and continue to fine tune

**Comment by sabman** [comment]
We are missing bannar image for https://github.com/geografia-au/geografia-au.github.io/blob/master/source/content/projects/rockingham_community_development_plan.md#L3

**Comment by sabman** [comment]
Image attached to this project is quite scary https://github.com/geografia-au/geografia-au.github.io/blob/master/source/content/projects/robinvale_family_centre_feasibility.md#L11 Do we have something better?

**Comment by sabman** [comment]
Missing high-res image for this https://github.com/geografia-au/geografia-au.github.io/blob/master/source/content/projects/southern_grampians_2015_economic_scorecard.md#L14

**Comment by Cesar-Nicolas** [comment]
Ah my apologies, I was simply working off the "Our Projects" list in the Dropbox folder.

Which is also related to the missing images. I had assumed that the projects in the Dropbox excel list are the final set to go live on the website, so if there are new images missing from the current website project list, then I assume @DrKLJ doesn't intend for them to be on the website? Which would mean they can be deleted I suppose?

**Comment by DrKLJ** [comment]
@sabman @Cesar-Nicolas Yes, that is right. Go with the 'our projects list'. I did this most recently by going through all 167 projects and selecting which ones I think should go up. Southern Grampians Scorecards and Rockingham CDP are not particularly interesting ones, so can leave out.
