### ISSUE TITLE
Minor Edit: Home page (3 work streams)

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#16]
We have 3 work streams with some definitions at the top. I would like to make some changes to them:
- [x] Change byline for economics to 'examining and modelling how our economies work'
- [x] Possibly change 'spatial planning' to 'spatial analysis'. NOTE. I would like people's views on that change. It seems to me we do spatial analysis, not planning, but what do you all think?  
- [x] If changing to spatial analysis, change byline to 'Understanding spatial patterns in our towns and cities'

**Comment by sabman** [comment]
@DrKLJ I prefer spatial analysis
