### ISSUE TITLE
Point geografia.com.au to the awesome new website

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#19]
https://help.github.com/articles/quick-start-setting-up-a-custom-domain/

**Comment by sabman** [comment]
@DrKLJ IMO the site is ready to go live - we can continue to make tweaks as needed via github. IF you give me the thumbs up we can turn off old machine and change to the new site

**Comment by DrKLJ** [comment]
@sabman Thumbs are up.

**Comment by sabman** [comment]
DNS records changed - we should be live within 24 hours
<img width="986" alt="" src="https://cloud.githubusercontent.com/assets/1907/19212914/e555a9d4-8d5d-11e6-8abe-3cbc07f344ef.png">

**Comment by sabman** [comment]
ref bdfa8156984b08e0c57af45674dc6aa20e0467e2
