### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#23]
@sabman Minor cosmetic enhancements (third one might not work).
- [x] make rim of the 3 circles at top of home page our red
- [ ] use the underline we use in our written material where we have lines (e.g. above associates and under each subheading, (see attached)
- [x] maybe use the three small red circles we use in written material (also in attached word document) next to each subheading (not sure about this one - could be messy or ugly/cluttered). 
  [underline.docx](https://github.com/geografia-au/geografia-au.github.io/files/504803/underline.docx)

**Comment by sabman** [comment]
@DrKLJ I have made it red on hover - having red on it's own looks strange.
I am not sure about what you mean by the 2nd point. Do you want a thicker line? or a mix of red and grey?
3rd point i'll ignore for now. 
<img width="694" alt="screenshot_10_2_16__11_58_am" src="https://cloud.githubusercontent.com/assets/1907/19019895/8888c21a-8897-11e6-9c14-4b42c62803ef.png">
Besides this and the better images for projects site is ready to go live.

**Comment by DrKLJ** [comment]
@sabman Attached is a report. If you look at it, you'll see we have these lines now on the top of each page. Partly red, partly grey. I thought we could reflect that where there is underlining on the website (e.g. under some of the headings. So rather than just a red line, its a line like the one in the report. Not sure what it will look like, but I like the idea of carrying over the design template. 
[Potential Impacts of NBN - Briefing Paper.docx](https://github.com/geografia-au/geografia-au.github.io/files/507679/Potential.Impacts.of.NBN.-.Briefing.Paper.docx)

**Comment by sabman** [comment]
A couple of issues with the line: 
1. it's quite challenging (fiddly) to manipulate borders in CSS and get them showing with multiple colors and still work across all screen sizes and devices (and i'm not an expert in it by any means nor do we have a designer with Advanced CSS/coding skills on the team, yet) 
2. Note how the pages have symmetry with the headings being centered - this would change the symmetry and IMHO probably not look so great. we can revisit this at a later stage if you feel necessary.
If you are ok with this can we close this issue for now?

**Comment by DrKLJ** [comment]
@sabman what if you made it it one line, centred and same as it currently is in all respects but that the first third of the line was red and other two thirds grey. Possible?

**Comment by sabman** [comment]
I just looked into it it's not - going to close for now.
