### ISSUE TITLE
Client logos

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#25]
@sabman @ziprandom Client logos seems to scroll through the same maybe 10 or so clients. But there should be about 80 logos to choose from.

**Comment by sabman** [comment]
@DrKLJ I need to make them transparent or download transparent versions of all of them. I did some but there are a lot more to do. I did some but if @Cesar-Nicolas has time he can gimme transparent versionse see https://github.com/geografia-au/geografia-au.github.io/tree/master/images/Geografia/clients

**Comment by Cesar-Nicolas** [comment]
@sabman no worries I will work on the logos, just wondering though, is it not possible to just code the transparency onto them i.e using CSS blending modes?

My only hesitation was that making the logos transparent via Photoshop puts them at risk of looking a little more "aliased" / edgy than simply using a blending mode to handle the white parts of the image. Would love to hear your thoughts.

**Comment by Cesar-Nicolas** [comment]
All done, this is the latest group of 74 client logos in total. Logos with a "T" on the end have been edited to make the background transparent, other logos have been untouched. They aren't perfectly transparent, but on any decently bright background, they are good enough.

[Geografia client logos transparent.zip](https://github.com/geografia-au/geografia-au.github.io/files/507452/Geografia.client.logos.transparent.zip)
