### ISSUE TITLE
Edited Content - Our Services Part 2

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#29]
@sabman - the rest of the points.
- [x] Housing demand analysis - Often working in collaboration with planners and urban designers, we apply modelling techniques to describe, explain, and predict patterns of price, supply of, and demand for, residential housing by dwelling type, household structure. The analysis informs the preparation of housing strategies. 
- [x]  Stakeholder engagement - Our IAP2 trained team help our clients work with community industry and government stakeholders through dialogue that teases out the social, environmental and economic issues that matter most.
- [x]  Demographic trend analysis - Let's ditch this one. It seems too similar to the population modelling. Instead, I suggest a slight re-write of the population modelling one (again) as per below. 
- [x] Population modelling, analysis and forecasting [**note title change**] - The world is full of interactions, ranging from simple to dynamic and complex. Many, if not all, affect how communities grow and change. The population modelling and forecasting we carry out describe how our populations might look in years to come and the policies and investments that will be most suited to support them.
- [x] Online decision support tools - We work with clients to develop browser-based decision support tools and expert systems to help them be more effective decision-makers. These tools integrate both qualitative and quantitative dimensions to the decision making.  
- [x] Economic modelling and analysis - Given the enormous complexity of economic processes we develop models that estimate and forecast economic activity, which can be used to design and test policy, investment planning and risk management.
- [x]  Labour market analysis [**note title change**] - Our models look at the suppliers of labour services (workers), the demands for labour services (employers), and helps explain the patterns of employment and the opportunities it might present in regions around Australia.
- [x] Economic impact and cost benefit - We help clients measure or estimate the change in economic activity in a specified region, caused by a change in business or policy circumstances. The study region can be a neighbourhood, town, city, county, statistical area, state, country, continent, or the entire globe and the results are used for business cases, what-if analysis and other studies. 
- [x]  Economic development and digital strategies - We prepare readable and achievable regional or industry-based economic development strategies. As economic activity moves into he digital realm, we are increasingly, turning to digital economy strategies, helping clients to take advantage of the digital economy.
- [x] Interactive atlases - We develop online atlases to help visualise and communicate the results of modelling and analysis. Spatial economic data is dynamic and deep. Rather than presenting this in static maps and tables, we prefer to compile interactive, online atlases for clients to explore and understand their economies in as much detail as they wish. 
- [x] Knowledge Economy Research - The emergence of knowledge-intense employment, where it agglomerates and why has been an area of research of ours for over a decade. More recently, we see that technology and, in particular, Artificial Intelligence is transforming a part of human knowledge to machines. This knowledge can be used in various fields and generate economic value. We are helping clients understand the impact of technology to their work.
- [x]  Spatial statistics and machine learning - We help clients understand how location impacts their work. To do this we apply the latest techniques from the fields of Statistics and Machine Learning.
- [x]  Service Demand Modelling - Using geospatial, demographic and economic data we help clients predict how demand for goods and services varies over time and geography and, therefore, how they can plan and locate their service provision to maximise efficiency and equity.
- [x]  Computational Geography - We apply the latest techniques in computation science to geographic problems to help clients make better decisions in planning, development and service provision.
- [x]  Geodata Visualisation - We have a strong focus on data visualisation and its ability to communicate patterns across space. 
- [x]  Land Use Analysis - We help our clients understand how changes in land use impacts social, environmental and economic issues. This is used to inform everything from master plans to infrastructure strategies and business cases. 
- [x]  Infrastructure needs assessment - We build models to forecast infrastructure demand so clients can decide on the most optimal infrastructure locations, the best use of funds and good policies that will address supply gaps. 
- [x] Survey data and collection - We build data collection systems which can incorporate geographic locations, thus bringing the spatial dimension to decision making.

**Comment by sabman** [comment]
@DrKLJ thanks! This is great!
