### ISSUE TITLE
Mobile version bug?

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#36]
@sabman I think there is a bug with the mobile display. The team images don't line up. They show 2 people at the top, then one person to the right below, rather than showing 4 people at once. See images. 
![screenshot_20161012-094955](https://cloud.githubusercontent.com/assets/15032298/19291569/c14a5402-9061-11e6-8e04-66184940d935.png)
![screenshot_20161012-095402](https://cloud.githubusercontent.com/assets/15032298/19291645/33309e78-9062-11e6-9398-72c0d1841827.png)

**Comment by sabman** [comment]
@DrKLJ it's not really a bug, it's coz there no hover in mobile. I'm not really sure what the alternative might look like but we can look at it tomorrow

**Comment by DrKLJ** [comment]
@sabman Okay. Its not a big drama. But if its something that can be corrected, that would be good.
