### ISSUE TITLE
Navigator bar issue - Safari 10.0

### ISSUE THREAD

**Issue by Cesar-Nicolas** [geografia-au/geografia-au.github.io#37]
Hello, just logging this issue I found while using Safari on a Mac.

![screen shot 2016-10-13 at 8 49 16 am](https://cloud.githubusercontent.com/assets/20567917/19329123/d7a73a64-9122-11e6-9055-92ef6884b55a.png)

**Comment by ziprandom** [comment]
assigning @sabman the owner of all things apple

**Comment by sabman** [comment]
<img width="1101" alt="menubar_and_geografia__demography__economics__spatial_analysis_and_open_and_geografia__demography__economics__spatial_analysis" src="https://cloud.githubusercontent.com/assets/1907/19550751/3fd073a2-96ab-11e6-8318-2c835b028651.png">
