### ISSUE TITLE
Provide Content: Home Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#4]
https://geografia-au.github.io/
## carousel slide needs have:

Carousel 1
- [ ] Text
- [ ] Call to action link

Carousel 2
- [ ] Text
- [ ] Call to action link

Carousel 3
- [ ] Text
- [ ] Call to action link
## OUR WORKS
- [ ] paragraph text
- [ ] better images for the top 12 projects
## OUR SERVICES
- [ ] paragraph text
## PARALLAX EFFECT
- [ ] change the title to "Recent Achievements"
- [ ] paragraph text
- [ ] 3 or 4 number - e.g.:
- projects completed, 
- happy customers, 
- reports published, 
- online apps
## OUR TEAM
- [ ] paragraph
## OUR RECENT POSTS
- [ ] paragraph
## OUR CUSTOMERS
- [ ] paragraph
- [ ] images of 272 x 180
## call to action
- [ ] update text and button for call to action

**Comment by DrKLJ** [comment]
@sabman @ziprandom Descriptive paragraphs plus recent achievements

Our team
Our team includes economists, demographers, planners, data scientists and web application developers. We combine a depth of experience with new talent and energy and work with a set of regular collaborators when we need to scale up. 

Our services
Our services range across economic and population modelling and impact analysis; developing online spatial, data visualisation and decision support tools; spatial analysis; and urban and regional planning. 

Recent Achievements
As well as all of our ongoing project work, we continue to invest in R&D, developing online apps, better modelling techniques and exploring new data; write short and long-form articles on our findings; and deliver conference papers aimed at improving the planning and development of our cities and towns. 

Projects completed: 167
Repeat clients: 44
Articles, book chapters and presentations prepared: 25
Online apps developed: 8

Our Works
We take on complex multi-disciplinary projects around Australia and in South East Asia, working in economics, demography and spatial planning. A selection of the hundreds of projects we have completed are described below. 

Our Customers
We work for all tiers of government, the private sector and not-for-profit entities: any organisations or people who need to understand complex economic, demographic and spatial data.

Our Recent Posts
Everyone at Geografia wants to share ideas to improve the places we live in and the way we all work. We share some of these ideas through these posts.

**Comment by DrKLJ** [comment]
@sabman @ziprandom 

Carousel slides:

Carousel 1
Text: We help solve the complex problems of development and planning in our cities, towns, economies and communities 
Link: to 'Services'

Carousel 2 
Text: We continuously invest in R&D 
Link: to 'Lab'

Carousel 3
Text: We share a lot of our ideas and R&D results through our favourite medium
Link to: Medium account

**Comment by DrKLJ** [comment]
@sabman Can you clarify further what help you are requesting under 'Call to Action' above?

**Comment by sabman** [comment]
@DrKLJ Call to Action I'm talking about is at the end home page currently says:

'Like what you see here? Checkout this theme and start to build your site immediately. LEARN MORE' 

I could imagine it saying want to work with us? get in touch (link to email us or contact page)
