### ISSUE TITLE
Dead Issue

### ISSUE THREAD

**Issue by DrKLJ** [geografia-au/geografia-au.github.io#47]

**Comment by sabman** [comment]
@DrKLJ Was it ever working?

**Comment by sabman** [comment]
I don't have access to an edge so can you please check if it works here: http://devoll.blahlab.com/

**Comment by DrKLJ** [comment]
@sabman 
Will check and let you know. It must have been working at one point as Liz uses Edge and has looked at site before.

**Comment by sabman** [comment]
Closing haven't received any feedback
