### ISSUE TITLE
Provide Content: About Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#5]
https://geografia-au.github.io/about/
## Banner
- [x] Background Image
- [x] Title
- [x] Subtile
## team images
- [x] Please provide me with exact image dimensions of 250x250px changing them in code is not acceptable - it leads to poor site performance and possible distortions

**Comment by DrKLJ** [comment]
@Cesar-Nicolas. I've added some photos here: Dropbox (Geografia)\Company Website\Geografia website\Staff photos, which you (Cesar) can use to create the 250X250 that Sabman needs. Ta.

**Comment by sabman** [comment]
@Cesar-Nicolas I have already done the images myself (you can see it's been marked off)

**Comment by sabman** [comment]
@DrKLJ @Cesar-Nicolas for future reference can we please make sure we 
use links rather than entering the folder names?  like so
https://www.dropbox.com/sh/ctyedkilvm5zgs6/AACIix9PZU1Zxj_hpLrcG-Y-a?dl=0

![dropbox-link](https://cloud.githubusercontent.com/assets/1907/18434910/5f19c0ca-78f0-11e6-919d-db3e84bcbf5f.gif)

I don't always have dropbox folders synced and this makes it quicker

**Comment by DrKLJ** [comment]
@cesar, can you fix Liz's photo? Hers has a dark background and ours don't. I think we have one of her with a light background. If not, can you create it?

**Comment by DrKLJ** [comment]
About Us
- [x] change byline to 'about us' to 'get to know a little about our purpose and our skills

[Suggest we use language from the business strategy session. the statements about what we are and what we do are: 

1 – Geografia are leaders in providing strategic insights on demography and economics for the purpose of confident decision making in local communities all over the world.
2 – Geografia uses its talented team of multidisciplinary professionals to conduct research and develop insights to inspire leaders and decision makers to create a better future for their communities.

I suggest a composite for the paragraph describing 'about us']
- [x] Intro text:
  Our History
  Geografia was formed in Australia in 2006, with the aim of bringing the techniques of complex systems analysis to how we plan for, develop and live in our cities, towns and regions. We now work around the country, as well as in SE Asia and Europe. 

We are a multidisciplinary team conducting research and developing insights in demography, economics and spatial planning to inspire leaders and decision-makers to create a better future for communities around the world. We bring together more than one expert in a range of fields and techniques. 
- [ ] Our skills: 
  Demography 33%
  Economics 33%
  Spatial Planning 50%
  Data Analytics 75%
  Applications Development 25%
  Consultation 60%
  Strategic Planning 50%

**Comment by sabman** [comment]
@DrKLJ do we have anything like client testimonials?

**Comment by DrKLJ** [comment]
We do, but they're old. Increasingly our clients are not inclined to provide them. I suggest we ditch that bit of the site.

**Comment by DrKLJ** [comment]
Just to be clear, they're not inclined to provide them because they're not allowed, not because we aren't worth it.
