### ISSUE TITLE
Point to Geografia Squarespace Site

### ISSUE THREAD

**Issue by Cesar-Nicolas** [geografia-au/geografia-au.github.io#52]
Hi @sabman, our Squarespace based site is ready to go live, please adjust geografia.com.au DNS records when you can, thanks!

---

From Squarespace Console:
This table shows you the DNS entries needed to connect your domain. Incorrect or missing entries are highlighted in red. Log in to your domain provider to manage these settings. If you need help adding and removing DNS entries, follow our step-by-step guide that walks you through the process.

Host | Record | Required Data | Current Data
-- | -- | -- | --
nhmlers7gbedyxg239zs | CNAME | verify.squarespace.com | Record not found
www | CNAME | ext-cust.squarespace.com | 206.51.242.1
@ | A | 198.185.159.144 | 206.51.242.1
@ | A | 198.185.159.145 | Record not found
@ | A | 198.49.23.144 | Record not found
@ | A | 198.49.23.145 | Record not found

Info: https://support.squarespace.com/hc/en-us/articles/205812378?flash_digest=4cfc627e2c6bfa0b5cbce5a5e50323edd9aca47c&platform=v6&websiteId=5a163263f6576eb8bfa002f6#toc-step-2---link-your-domain

**Comment by sabman** [comment]
Done. Looks nice! Not sure if getting rid of the Products menu was a deliberate choice. the SSL warning will going away within 72 hours

**Comment by Cesar-Nicolas** [comment]
Great, thanks for this! Actually, good spot, was focused on just getting the MVP out, will add the missing pages soon!

**Comment by Cesar-Nicolas** [comment]
![image](https://user-images.githubusercontent.com/20567917/39729204-fff549fa-529d-11e8-921f-65b2888feb33.png)

![image](https://user-images.githubusercontent.com/20567917/39729761-edb3325e-52a0-11e8-92f4-07aac487c0f9.png)

**Comment by Cesar-Nicolas** [comment]
Also just a note, fonts were acting weird because I forgot we were dependent on an Adobe Typekit. I have fixed this by adding the domain to the allowed sites.

![image](https://user-images.githubusercontent.com/20567917/39731616-f62deb26-52ab-11e8-8ff2-96ea6b0603b4.png)

**Comment by sabman** [comment]
@Cesar-Nicolas excellent! I'm glad you mentioned it here. It's important we have an audit trail of this. Can you add the password for typekit to our password manager (@DrKLJ we need a passwords/tokens manager ASAP) I recommend 1Password. The current situation of putting them in a wiki is highly unsatisfactory
