### ISSUE TITLE
Provide Content: Services Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#6]
see: https://geografia-au.github.io/services/
## our services banner
- [x] background image 2400x1600 https://geografia-au.github.io/company-site-jekyll/images/@stock/service-page-header.jpg
- [x] list services we provide - preferably even number and a small description

---

For web team:
- [x] add a call to action button at the end of the services with following text and link: [[ Hire us ]](mailto:info@geografia.com.au?subject=hire geografia)

**Comment by DrKLJ** [comment]
@sabman Can you describe to me how this works with the drop down list of projects we've completed under the 3 work areas (demography, economics, spatial planning)?

**Comment by sabman** [comment]
@DrKLJ If we look at only these 3 areas then this list is too long. IMO we can expand on that? 

I thought we could drill down into these 3 areas, so for spatial planning:
- Spatial Statistics & Machine Learning
- Computation Geography
- GeoData Visualization

Some candidates for additional services:
- Big GeoData Analytics
- Hydrographic Data Analysis
- Remote Sensing & Spatial Analysis
- Location Based Services and Mobile Apps
- GeoAnalysis of Social Media Data

We definitely have expertise in the areas 😄 But if you disagree we can probably get rid of this page.

**Comment by DrKLJ** [comment]
Currently we have an 'our services' part of the home page. This is a separate section. Doesn't having what is effectively 2 'Our Services' sections confuse things? What about the link at top of home page going to the current 'our services' component on the home page, rather than to a more comprehensive 'Our Services' section. What do you think? 

Also, in our 'about us' page we already talk about skills (the bar chart with the %s (which I calculated by allocating competency to the 8 people on the website). Again, too much? About us should be the skills we have; services should be more about the projects we do, no?

**Comment by sabman** [comment]
@DrKLJ Services are an expansion on the skills we have - yes there is some repetition but it probably has more than what's on the homepage services section

**Comment by DrKLJ** [comment]
@sabman Okay, I will write something up, then.

**Comment by DrKLJ** [comment]
@sabman 

Not sure if it will work as a set of lists, but see what you think: 

Services: 
[byline] Across the disciplines of demography, economics and spatial analysis we provide a range of quantitative and qualitative analytical services. 

Demography 
• Population modelling and forecasting
• Scenario planning
• Infrastructure supply-demand modelling
• Housing demand analysis
• Stakeholder engagement
• Demographic trend analysis
• Online decision support tools

Economics
• Economic modelling and analysis
• Labour market modelling
• Economic impact and cost benefit
• Economic development and digital strategies
• Interactive atlases
• Knowledge economy research

Geodata analytics 
• Spatial Statistics and machine learning
• Service demand modelling 
• Computational geography
• Geodata visualisation 
• Land use analysis
• Infrastructure needs assessment
• Survey data and collection
