### ISSUE TITLE
Add Lab Page

### ISSUE THREAD

**Issue by sabman** [geografia-au/geografia-au.github.io#7]
**Make it similar to Projects page with links to the following projects:**
- [x] http://geografia-au.github.io/city-atlas/
- [x] take a screenshot for the thumbnail
- [x] text: The City Atlas is a project by Geografia exploring spatial patterns across metropolitan areas. It is designed to illustrate current and future employment and service accessibility.

---
- [x] http://geografia-au.github.io/lab-port-phillip/
- [x] screenshot
- [x] text: This visualisation shows forecasted changes in population for the City of Port Phillip at the statistical area 1 (SA1) level.

---
- [x] http://geografia.com.au/victowns/index.html#
- [x] screenshot
- [x] text: VicTowns provides a score-card for Victoria's rural and regional towns. Each score measures access to important facilities, services and economic opportunity.

**Comment by ziprandom** [comment]
8f6bf8c9e264c163f9948cb604f907580b4278d2, 2644444ac0e8cd30211ec60a552bd8d953bfe66d, 64f8452bf29919e52ba859cd52e56ef7ea18584e, d598fff49ef7a9c8e8568397dc1aa631941fda73

**Comment by ziprandom** [comment]
f26838443fbadeb29e6c848ff5ccf59abe59434d, 422a520b6b3731f4e28ca9d58e9f27559dac18f5, 057b331c6d76dbb9e903342f6fc452bb095cf35f
